--@Autor(es): Emmanuel Jimenez / Jesus Tenorio
--@Fecha creación: 08/12/2025
--@Descripción: Script para clonar las PDBs por módulo

Prompt Conectando como sys
connect sys/system0 as sysdba

whenever sqlerror exit rollback

create pluggable database proveedores
  admin user proveedores_admin identified by proveedores_admin
  file_name_convert = ('/opt/oracle/oradata/FREE/pdbseed', 
    '/unam/bda/pf/pdbs/proveedores');

Prompt Abrir la PDB proveedores
alter pluggable database proveedores open;

Prompt Guardar el estado de la PDB
alter pluggable database proveedores save state;

create pluggable database servicios
  admin user servicios_admin identified by servicios_admin
  file_name_convert = ('/opt/oracle/oradata/FREE/pdbseed', 
    '/unam/bda/pf/pdbs/servicios');

Prompt Abrir la PDB servicios
alter pluggable database servicios open;

Prompt Guardar el estado de la PDB
alter pluggable database servicios save state;


/*
Cambiarse a usuario oracle
ir a la ruta $ORACLE_HOME/network/admin
crear archivo tnsnames.ora y agregar el siguiente contenido

# tnsnames.ora Network Configuration File: /opt/oracle/product/23ai/dbhomeFree/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.

FREE =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = free.fi.unam)
    )
  )

LISTENER_FREE =
  (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))

PROVEEDORES =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = proveedores.fi.unam)
    )
  )

SERVICIOS =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = servicios.fi.unam)
    )
  )


Cambiar los permisos al archivo chmod 755 tnsnames.ora

Sin cambiar de usuario cambiarse a $ORACLE_HOME/sqlplus/admin
abrir nano gloglin.sql
agregar:

define _editor=nano
--personalizar el prompt
define prompt_value=idle
col prompt_name new_value prompt_value
col prompt_name noprint
set heading off
set termout off
select lower(sys_context('userenv','current_user')
||'@'
||sys_context('userenv','db_name'))
as prompt_name
from dual;
set sqlprompt '&prompt_value> '
set heading on
set termout on
col prompt_name print
set trimspool on

cambiar permisos chmod 755 glogin.sql
*/