--@Autor(es):       Emmanuel Jimenez / Jesus Tenorio
--@Fecha creación:  09/12/2025
--@Descripción:     Script para habilitar modo compartido y pool de conexiones
--                  

Prompt Conectando como sys en cdb$root
connect sys/system0 as sysdba

Prompt Modificando parametro processes a 300
alter system set processes=300 scope=spfile;

Prompt Reiniciar instancia
shutdown immediate
startup

Prompt Conectando nuevamente como sys en cdb$root
connect sys/system0 as sysdba

alter system set dispatchers='(dispatchers=3)(protocol=tcp)' scope=spfile;
alter system set shared_servers=10 scope=spfile;
alter system register;

exec dbms_connection_pool.start_pool();
exec dbms_connection_pool.alter_param ('','MAXSIZE','50');
exec dbms_connection_pool.alter_param ('','MINSIZE','36');
exec dbms_connection_pool.alter_param ('','INACTIVITY_TIMEOUT','1800');
exec dbms_connection_pool.alter_param ('','MAX_THINK_TIME','1800');

Prompt Conectando a proveedores como shared
connect prov_admin/1234@proveedores_shared

Prompt Conectando a servicios como shared
connect serv_admin/1234@servicios_shared

Prompt Conectando a proveedores como shared
connect prov_admin/1234@proveedores_pooled

Prompt Conectando a servicios como shared
connect serv_admin/1234@servicios_pooled

-- Contenido de tnsnames.ora
/*
# tnsnames.ora Network Configuration File: /opt/oracle/product/23ai/dbhomeFree/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.

FREE =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = free.fi.unam)
    )
  )

LISTENER_FREE =
  (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))

PROVEEDORES =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = proveedores.fi.unam)
    )
  )

SERVICIOS =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = servicios.fi.unam)
    )
  )

PROVEEDORES_SHARED =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = SHARED)
      (SERVICE_NAME = proveedores.fi.unam)
    )
  )

SERVICIOS_SHARED =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = SHARED)
      (SERVICE_NAME = servicios.fi.unam)
    )
  )

PROVEEDORES_POOLED =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = proveedores.fi.unam)
      (SERVER=POOLED)
    )
  )

SERVICIOS_POOLED =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = h-ejc-proy-final.fi.unam)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = servicios.fi.unam)
      (SERVER=POOLED)
    )
  )

*/

